# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andy_shen/code/knn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andy_shen/code/knn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andy_shen/code/knn/CMakeFiles /home/andy_shen/code/knn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andy_shen/code/knn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named knn

# Build rule for target.
knn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 knn
.PHONY : knn

# fast build rule for target.
knn/fast:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/build
.PHONY : knn/fast

# target to build an object file
data.o:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/data.o
.PHONY : data.o

# target to preprocess a source file
data.i:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/data.i
.PHONY : data.i

# target to generate assembly for a file
data.s:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/data.s
.PHONY : data.s

# target to build an object file
knn.o:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/knn.o
.PHONY : knn.o

# target to preprocess a source file
knn.i:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/knn.i
.PHONY : knn.i

# target to generate assembly for a file
knn.s:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/knn.s
.PHONY : knn.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/main.s
.PHONY : main.s

# target to build an object file
sort.o:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/sort.o
.PHONY : sort.o

# target to preprocess a source file
sort.i:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/sort.i
.PHONY : sort.i

# target to generate assembly for a file
sort.s:
	$(MAKE) -f CMakeFiles/knn.dir/build.make CMakeFiles/knn.dir/sort.s
.PHONY : sort.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... knn"
	@echo "... data.o"
	@echo "... data.i"
	@echo "... data.s"
	@echo "... knn.o"
	@echo "... knn.i"
	@echo "... knn.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

